-- ============================================================================
-- CivicConnect — Core Schema (Supabase / PostgreSQL)
-- ============================================================================
-- Design principle: USER_IDENTITY is stored separately from COMPLAINT_RECORD.
-- Officials and other citizens query views/functions that never join back to
-- identity tables. Only rows in audit_logs (write-only, restricted read) can
-- link a complaint to a person, and only for authorized security/audit roles.
-- ============================================================================

create extension if not exists "uuid-ossp";
create extension if not exists postgis; -- for ward polygon / point-in-polygon lookups

-- ---------------------------------------------------------------------------
-- 1. Jurisdiction hierarchy (configurable — NOT hardcoded to one region)
-- ---------------------------------------------------------------------------
create table countries (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique
);

create table states (
  id uuid primary key default uuid_generate_v4(),
  country_id uuid references countries(id) not null,
  name text not null,
  unique(country_id, name)
);

create table districts (
  id uuid primary key default uuid_generate_v4(),
  state_id uuid references states(id) not null,
  name text not null,
  unique(state_id, name)
);

create table sub_districts ( -- Tehsil / Taluka
  id uuid primary key default uuid_generate_v4(),
  district_id uuid references districts(id) not null,
  name text not null,
  unique(district_id, name)
);

create table villages ( -- also covers municipal regions
  id uuid primary key default uuid_generate_v4(),
  sub_district_id uuid references sub_districts(id) not null,
  name text not null,
  is_urban boolean default false,
  unique(sub_district_id, name)
);

create table wards (
  id uuid primary key default uuid_generate_v4(),
  village_id uuid references villages(id) not null,
  name text not null,
  boundary geometry(Polygon, 4326), -- ward polygon for point-in-polygon checks
  unique(village_id, name)
);
create index wards_boundary_gix on wards using gist (boundary);

-- ---------------------------------------------------------------------------
-- 2. Identity — separated from complaint data
-- ---------------------------------------------------------------------------
-- auth.users is Supabase-managed. This table extends it privately.
create table user_identity (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  username text unique not null,
  email text unique not null,
  phone text,
  created_at timestamptz default now()
);
-- RLS: a citizen can only read/update their OWN row. No official role can
-- select from this table at all (enforced in policies file).

create type app_role as enum (
  'CITIZEN',
  'WARD_COUNCILLOR',
  'VILLAGE_HEAD',
  'TEHSILDAR_SDM',
  'DM_COLLECTOR',
  'CM',
  'PM_CENTRAL_ADMIN',
  'AUDIT_ADMIN' -- narrow, legally-scoped identity access only
);

create table roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role app_role not null default 'CITIZEN',
  -- jurisdiction scoping for officials (nulls for CITIZEN / PM_CENTRAL_ADMIN)
  ward_id uuid references wards(id),
  village_id uuid references villages(id),
  sub_district_id uuid references sub_districts(id),
  district_id uuid references districts(id),
  state_id uuid references states(id),
  issued_by text, -- government office reference, for officials only
  is_government_issued boolean default false,
  created_at timestamptz default now()
);
-- IMPORTANT: the mobile client NEVER sets its own role. Only a trusted
-- backend process (service_role, or an admin-only RPC) may insert/update
-- this table. RLS below denies client-side writes entirely.

create table citizen_home_ward (
  user_id uuid primary key references auth.users(id) on delete cascade,
  ward_id uuid references wards(id) not null,
  verified_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- 3. Complaints
-- ---------------------------------------------------------------------------
create type complaint_category as enum (
  'CRIME','COMMUNITY','INFRASTRUCTURE','ENVIRONMENT','WATER','ELECTRICITY',
  'ROADS','STREET_LIGHTS','SANITATION','GARBAGE','DRAINAGE','PUBLIC_SAFETY',
  'TRAFFIC','OTHER'
);
create type complaint_status as enum (
  'PENDING','VERIFIED','ASSIGNED','IN_PROGRESS','RESOLVED','REJECTED','ESCALATED'
);
create type verification_status as enum (
  'UNVERIFIED','VERIFYING','VERIFIED','REJECTED'
);

create table complaints (
  id uuid primary key default uuid_generate_v4(),
  display_id text unique not null, -- e.g. CMP12345, generated by trigger
  category complaint_category not null,
  description text not null,
  severity smallint not null check (severity between 1 and 5),

  -- geo: exact coordinates are sensitive and access-restricted (see RLS)
  latitude double precision not null,
  longitude double precision not null,
  approximate_location text, -- public-safe label, e.g. "Near Gomti Nagar market"

  country_id uuid references countries(id) not null,
  state_id uuid references states(id) not null,
  district_id uuid references districts(id) not null,
  sub_district_id uuid references sub_districts(id) not null,
  village_id uuid references villages(id) not null,
  ward_id uuid references wards(id), -- nullable: crime reports may not require jurisdiction match

  reporter_id uuid references auth.users(id) not null, -- never exposed directly to officials
  is_anonymous boolean not null default true, -- always true for official/community-facing views

  status complaint_status not null default 'PENDING',
  verification_status verification_status not null default 'UNVERIFIED',
  community_verified boolean default false,
  government_verified boolean default false,

  upvote_count integer not null default 0,
  priority_score numeric not null default 0,

  assigned_authority_role app_role,
  assigned_authority_user_id uuid references auth.users(id),

  is_crime boolean generated always as (category = 'CRIME') stored,
  geo_lock_exempt boolean generated always as (category = 'CRIME') stored,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  assigned_at timestamptz,
  resolved_at timestamptz,
  escalated_at timestamptz
);
create index complaints_ward_idx on complaints(ward_id);
create index complaints_status_idx on complaints(status);
create index complaints_priority_idx on complaints(priority_score desc);

create sequence complaint_display_id_seq start 10000;
create or replace function set_complaint_display_id() returns trigger as $$
begin
  new.display_id := 'CMP' || nextval('complaint_display_id_seq');
  return new;
end;
$$ language plpgsql;
create trigger trg_complaint_display_id before insert on complaints
  for each row execute function set_complaint_display_id();

create table complaint_images (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  storage_path text not null, -- Supabase Storage object path; EXIF stripped at upload time (edge function)
  uploaded_at timestamptz default now()
);

create table complaint_status_history (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  previous_status complaint_status,
  new_status complaint_status not null,
  changed_by uuid references auth.users(id),
  changed_by_role app_role,
  note text,
  created_at timestamptz default now()
);

create table complaint_votes (
  complaint_id uuid references complaints(id) on delete cascade not null,
  user_id uuid references auth.users(id) not null,
  created_at timestamptz default now(),
  primary key (complaint_id, user_id) -- enforces one vote per citizen per complaint at the DB level
);

create table complaint_comments (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  author_id uuid references auth.users(id) not null, -- never surfaced to clients; UI always shows "Anonymous Citizen"
  parent_comment_id uuid references complaint_comments(id),
  body text not null,
  is_flagged boolean default false,
  created_at timestamptz default now()
);

create table complaint_verifications (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  verified_by uuid references auth.users(id) not null,
  verifier_role app_role not null,
  result verification_status not null,
  note text,
  created_at timestamptz default now()
);

create table complaint_assignments (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  assigned_role app_role not null,
  assigned_user_id uuid references auth.users(id),
  assigned_at timestamptz default now(),
  deadline_at timestamptz not null, -- created_at + configurable SLA (default 14 days)
  resolved_within_deadline boolean
);

create table complaint_escalations (
  id uuid primary key default uuid_generate_v4(),
  complaint_id uuid references complaints(id) on delete cascade not null,
  from_role app_role not null,
  to_role app_role not null,
  from_user_id uuid references auth.users(id),
  to_user_id uuid references auth.users(id),
  days_pending integer not null,
  reason text not null default 'Complaint exceeded the configured resolution window.',
  created_at timestamptz default now()
  -- Immutable: no update/delete grants on this table for any role, including admins.
);

create table notifications (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) not null,
  complaint_id uuid references complaints(id),
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- 4. Audit log — immutable, append-only, restricted read
-- ---------------------------------------------------------------------------
create table audit_logs (
  id uuid primary key default uuid_generate_v4(),
  actor_user_id uuid references auth.users(id),
  actor_role app_role,
  action text not null, -- e.g. 'STATUS_CHANGE', 'IDENTITY_ACCESS', 'VERIFICATION'
  target_table text not null,
  target_id uuid,
  previous_value jsonb,
  new_value jsonb,
  created_at timestamptz default now()
);
-- No update or delete grants issued on audit_logs to any application role.

-- ---------------------------------------------------------------------------
-- 5. Escalation configuration (per-category SLA, configurable chain)
-- ---------------------------------------------------------------------------
create table escalation_rules (
  id uuid primary key default uuid_generate_v4(),
  category complaint_category not null unique,
  sla_days integer not null default 14,
  chain app_role[] not null default array[
    'WARD_COUNCILLOR','VILLAGE_HEAD','TEHSILDAR_SDM','DM_COLLECTOR','CM','PM_CENTRAL_ADMIN'
  ]::app_role[]
);

comment on table escalation_rules is
  'One row per category so legally mandated timelines can differ per category in production; the chain array lets each jurisdiction configure its own hierarchy rather than hardcoding one structure for all of India.';
